movies/urls.py
from django.conf.urls import url

from . import views

app_name = "movies"

urlpatterns = [
	# /
    url(r'^$', views.IndexView.as_view(), name='index'),

    # /list
    url(r'^list/$', views.ListView.as_view(), name='list'),

    # /424/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
]

project/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
	url(r'^', include('movies.urls')),
    url(r'^admin/', admin.site.urls),
]

movies/models.py
from django.db import models

# Create your models here.
class Genre(models.Model):
	name = models.CharField(max_length=250)

	def __str__(self):
		return self.name

class Organization(models.Model):
	name = models.CharField(max_length=250)

	def __str__(self):
		return self.name

class Person(models.Model):
	name = models.CharField(max_length=250)

	def __str__(self):
		return self.name

class Movie(models.Model):
	position = models.IntegerField()
	name = models.CharField(max_length=250)
	picture = models.CharField(max_length=500)
	score = models.IntegerField(null=True)
	description = models.TextField()
	production_company = models.ForeignKey(Organization, on_delete=models.CASCADE, null=True)
	genre = models.ManyToManyField(Genre, related_name="genre")
	director = models.ManyToManyField(Person, related_name="director")
	author = models.ManyToManyField(Person, related_name="author")
	actor = models.ManyToManyField(Person, related_name="actor")

	def __str__(self):
		return self.name

class Critic(models.Model):
	text = models.TextField()
	url = models.CharField(max_length=250)
	author = models.ForeignKey(Person, on_delete=models.CASCADE)
	publisher = models.ForeignKey(Organization, on_delete=models.CASCADE)
	movie = models.ForeignKey(Movie, related_name="critics")

	def __str__(self):
		return self.publisher.name + ' - ' + self.author.name

movies/views.py
from django.views import generic
from .models import Movie, Critic

class IndexView(generic.ListView):
	template_name = 'movies/index.html'
	context_object_name = 'movies'

	def get_queryset(self):
		return Movie.objects.order_by('position')[:5]

class ListView(generic.ListView):
	template_name = 'movies/list.html'
	context_object_name = 'movies'

	def get_queryset(self):
		return Movie.objects.order_by('position')

class DetailView(generic.DetailView):
	model = Movie
	template_name = 'movies/detail.html'

	def get_context_data(self, **kwargs):
	        context = super(DetailView, self).get_context_data(**kwargs)
	        pk = self.kwargs["pk"]
	        context['critics'] = Critic.objects.filter(movie=pk)
	        return context

movies/templates/movies/base.html
<!DOCTYPE html>
<html>
	<head>
		<title>Movies</title>
		<meta charset="utf-8">

		{% load staticfiles %}
		<!-- Font Awesome -->
		<link rel="stylesheet" href="{% static 'libs/font-awesome/css/font-awesome.min.css' %}">
		<!-- Bootstrap CSS -->
		<link rel="stylesheet" href="{% static 'libs/bootstrap/css/bootstrap.min.css' %}">
		<!-- Custom CSS -->
		<link rel="stylesheet" href="{% static 'style.css' %}">
	</head>
	<body>

		<nav class="navbar navbar-inverse">
		  <div class="container-fluid">
		    <div class="navbar-header">
		      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#myTopNavbar" aria-expanded="false">
		        <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		      </button>
		      <a class="navbar-brand" href="{% url 'movies:index' %}">Movies</a>
		    </div>
		    <div class="collapse navbar-collapse" id="myTopNavbar">
		      <ul class="nav navbar-nav">
		        <li class="{% url 'movies:index' as index_url %} {% if request.path == index_url %} active {% endif %}"><a href="{% url 'movies:index' %}">Top 5</a></li>
		        <li class="{% url 'movies:list' as index_url %} {% if request.path == index_url %} active {% endif %}"><a href="{% url 'movies:list' %}">List of all</a></li>
		      </ul>
		    </div>
		  </div>
		</nav>

		{% block body %}
		{% endblock %}

		<!-- Jquery -->
		<script src="{% static 'libs/jquery-2.1.4.min.js' %}"></script>
		<!-- Bootstrap JS -->
		<script src="{% static 'libs/bootstrap/js/bootstrap.min.js' %}"></script>
	</body>
</html>

movies/templates/movies/detail.html
{% extends 'movies/base.html' %}

{% block body %}
<div class="container">

<div class="col-md-9">

    <div class="row">
        <div class="col-md-5">
            <a href="">
                <img src="{{movie.picture}}" class="img-rounded" width="300" height="500">
            </a>
        </div>
        <div class="col-md-7">
            <h2>{{movie.name}} ({% if movie.score %}{{movie.score}}%{% else %}no score yet{% endif %})</h2>
            {% if movie.production_company.name %}<h3>{{movie.production_company}}</h3>{% endif %}

            <h4>Description:</h4>
            <p>{{movie.description}}</p>

            <h4>Genre:</h4>
            <p>
            {% for genre in movie.genre.all %}
                {{genre.name}}{% if forloop.last == False %},{% else %}.{% endif %} 
            {% endfor %}

            {% if movie.genre.all|length == 0 %}
                <i>No genre.</i>
            {% endif %}
            </p>

            <h4>Director:</h4>
            <p>
            {% for director in movie.director.all %}
                {{director.name}}{% if forloop.last == False %},{% else %}.{% endif %} 
            {% endfor %}
            {% if movie.director.all|length == 0 %}
                <i>No director.</i>
            {% endif %}
            </p>

            <h4>Author:</h4>
            <p>
            {% for author in movie.author.all %}
                {{author.name}}{% if forloop.last == False %},{% else %}.{% endif %} 
            {% endfor %}
            {% if movie.author.all|length == 0 %}
                <i>No author.</i>
            {% endif %}
            </p>

            <h4>Cast:</h4>
            <p>
            {% for actor in movie.actor.all %}
                {{actor.name}}{% if forloop.last == False %},{% else %}.{% endif %} 
            {% endfor %}
            {% if movie.actor.all|length == 0 %}
                <i>No cast.</i>
            {% endif %}
            </p>
        
        </div>
    </div>
    <div class="row">
        <div class="col-md-10">

            <h3>Critics:</h3>
            {% for critic in critics.all %}
                <h4><a href="{{critic.url}}" target="_blank">{{critic.publisher}}</a> - {{critic.author}}</h4>
                <p>{{critic.text}}</p><hr>
            {% endfor %}
            {% if critics.all|length == 0 %}
                <p><i>No critics.</i></p>
            {% endif %}

        </div>
    </div>

</div>

</div>
{% endblock %}

movies/templates/movies/index.html
{% extends 'movies/base.html' %}

{% block body %}
<div class="container">

<div class="col-md-8">

	{% for movie in movies %}
    <div class="row">
        <div class="col-md-3">
            <a href="{% url 'movies:detail' movie.id %}">
                <img src="{{movie.picture}}" class="img-rounded" width="130" height="200">
            </a>
        </div>
        <div class="col-md-9">
            <h3>{{forloop.counter}}. {{movie.name}} ({% if movie.score %}{{movie.score}}%{% else %}no score yet{% endif %})</h3>
            {% if movie.production_company.name %}<h4>{{movie.production_company}}</h4>{% endif %}
            <p>{{movie.description}}</p>
            <a class="btn btn-primary" href="{% url 'movies:detail' movie.id %}">More <span class="glyphicon glyphicon-chevron-right"></span></a>
        </div>
    </div>
    <hr>
    {% endfor %}

</div>

</div>
{% endblock %}

movies/templates/movies/list.html
{% extends 'movies/base.html' %}

{% block body %}
<div class="container">

	<div class="row">
	{% for movie in movies %}

		{% if forloop.counter0|divisibleby:6 %}
			</div>
			<div class="row">
		{% endif %}

		        <div class="col-md-2 portfolio-item">
		            <a href="{% url 'movies:detail' movie.id %}">
		                <img src="{{movie.picture}}" class="img-rounded" width="130" height="200">
		            </a>
		            <h4>
		                <a href="{% url 'movies:detail' movie.id %}">{{movie.name}} ({% if movie.score %}{{movie.score}}%{% else %}no score yet{% endif %})</a>
		            </h4>
		            <br>
		        </div>

	{% endfor %}

</div>
{% endblock %}